# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12ff7bc5354cc59b7b6c499660f6245ace601e8b49d0a3cfd9ad0642b0a2c9c569ee96e3b90b16d4795a80bc1293e3f93013e310e5f49f7a17f977b9eacb00af

test:
  secret_key_base: 9953767da15bcb5df4fc8bfadeb19da79c71726ec6f7003ec367fe0c57814162d91e267d90fc888e1aeeb5ce09cd1cd4fed3890c38a84504c69063e791f2ae90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
